Fixed errors reported if we invoke ConfigParser.set() :
TypeError: must be type, not classobj

That cause by the object style of ConfigParser in python 2.x, in python 3.x, the ConfigParser has changed to new-style object, set() invoke method has changed.